import { faker } from "@faker-js/faker";
import { PrismaClient } from "@prisma/client";

export async function insertEventos(prisma: PrismaClient) {
  const dataAtual = new Date();

  await prisma.evento.createMany({
    data: [
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "US - Transvaginal (útero, ovário, anexos e vagina)",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        teveInternacao: true,
        idCid: 1,
        idPrestador: 1,
        idPessoa: 1,
        idProcedimento: 1,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 2,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - planejamento e 1º dia de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 1,
        idPrestador: 1,
        idPessoa: 1,
        idProcedimento: 1,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "CATETER INTRAVENOSO PERIFERICO 24G 100UNID",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 2,
        idPrestador: 2,
        idPessoa: 2,
        idProcedimento: 2,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "SERINGA S/AG.10ML LUER-LOK PLASTIPAK",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 2,
        idPrestador: 2,
        idPessoa: 2,
        idProcedimento: 2,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 1,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta odontológica",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 3,
        idPrestador: 3,
        idPessoa: 3,
        idProcedimento: 3,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 1,
          dataAtual.getDate() + 10
        ),
        quantidade: 2,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 3,
        idPrestador: 3,
        idPessoa: 3,
        idProcedimento: 3,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 1,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao:
          "Angio-RM (crânio ou pescoço ou tórax ou abdome superior ou pelve) - arterial ou venosa",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 4,
        idPrestador: 4,
        idPessoa: 4,
        idProcedimento: 4,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 1,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao:
          "Angio-RM (crânio ou pescoço ou tórax ou abdome superior ou pelve) - arterial ou venosa",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 4,
        idPrestador: 4,
        idPessoa: 4,
        idProcedimento: 4,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta odontológica",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 5,
        idPrestador: 4,
        idPessoa: 5,
        idProcedimento: 5,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Herniorrafia umbilical",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 5,
        idPrestador: 1,
        idPessoa: 5,
        idProcedimento: 5,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 6,
        idPrestador: 2,
        idPessoa: 1,
        idProcedimento: 6,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Herniorrafia umbilical",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 6,
        idPrestador: 3,
        idPessoa: 2,
        idProcedimento: 6,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 1,
        idPrestador: 3,
        idPessoa: 2,
        idProcedimento: 7,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Tomografia",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 6,
        idPrestador: 3,
        idPessoa: 2,
        idProcedimento: 7,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 2,
        idPrestador: 4,
        idPessoa: 3,
        idProcedimento: 8,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - por dia subsequente de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 2,
        idPrestador: 4,
        idPessoa: 3,
        idProcedimento: 8,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 4,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 3,
        idPrestador: 1,
        idPessoa: 4,
        idProcedimento: 9,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 4,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - por dia subsequente de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 3,
        idPrestador: 1,
        idPessoa: 4,
        idProcedimento: 9,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 4,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 4,
        idPrestador: 2,
        idPessoa: 5,
        idProcedimento: 10,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 4,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Hemo",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 3,
        idPrestador: 1,
        idPessoa: 4,
        idProcedimento: 10,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 1,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 5,
        idPrestador: 3,
        idPessoa: 1,
        idProcedimento: 11,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 1,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Hemo",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 6,
        idPrestador: 4,
        idPessoa: 5,
        idProcedimento: 11,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 6,
        idPrestador: 4,
        idPessoa: 2,
        idProcedimento: 12,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Hemo",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 1,
        idPrestador: 4,
        idPessoa: 3,
        idProcedimento: 12,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 6,
        idPrestador: 4,
        idPessoa: 2,
        idProcedimento: 12,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - planejamento e 1º dia de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 1,
        idPrestador: 4,
        idPessoa: 3,
        idProcedimento: 12,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 1,
        idPrestador: 1,
        idPessoa: 3,
        idProcedimento: 13,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - planejamento e 1º dia de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 1,
        idPrestador: 1,
        idPessoa: 3,
        idProcedimento: 13,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 2,
        idPrestador: 2,
        idPessoa: 3,
        idProcedimento: 14,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - planejamento e 1º dia de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 3,
        idPrestador: 4,
        idPessoa: 3,
        idProcedimento: 14,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 3,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 3,
        idPrestador: 3,
        idPessoa: 4,
        idProcedimento: 15,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - planejamento e 1º dia de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 4,
        idPrestador: 4,
        idPessoa: 5,
        idProcedimento: 15,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 4,
        idPrestador: 4,
        idPessoa: 5,
        idProcedimento: 16,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - planejamento e 1º dia de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        idCid: 5,
        idPrestador: 1,
        idPessoa: 1,
        idProcedimento: 16,
        teveInternacao: true,
      },
    ],
  });
}
