import { faker } from "@faker-js/faker";
import { PrismaClient } from "@prisma/client";

export async function insertEventos(prisma: PrismaClient) {
  const dataAtual = new Date();

  await prisma.evento.createMany({
    data: [
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "US - Transvaginal (útero, ovário, anexos e vagina)",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        teveInternacao: true,
        codigoCID: "J80",
        idPrestador: 1,
        idPessoa: 1,
        idProcedimento: 1,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 2,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - planejamento e 1º dia de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        codigoCID: "J80",
        idPrestador: 1,
        idPessoa: 1,
        idProcedimento: 1,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "CATETER INTRAVENOSO PERIFERICO 24G 100UNID",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        codigoCID: "B34",
        idPrestador: 2,
        idPessoa: 2,
        idProcedimento: 2,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "SERINGA S/AG.10ML LUER-LOK PLASTIPAK",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        codigoCID: "B34",
        idPrestador: 2,
        idPessoa: 2,
        idProcedimento: 2,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 1,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Consulta odontológica",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        codigoCID: "U04",
        idPrestador: 3,
        idPessoa: 3,
        idProcedimento: 3,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 1,
          dataAtual.getDate() + 10
        ),
        quantidade: 2,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        codigoCID: "U04",
        idPrestador: 3,
        idPessoa: 3,
        idProcedimento: 3,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 1,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao:
          "Angio-RM (crânio ou pescoço ou tórax ou abdome superior ou pelve) - arterial ou venosa",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "ALTO",
        prontoSocorro: true,
        UTI: false,
        tipoInternacao: "CIRURGICA",
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "A00",
        idPrestador: 4,
        idPessoa: 10,
        idProcedimento: 4,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 1,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao:
          "Angio-RM (crânio ou pescoço ou tórax ou abdome superior ou pelve) - arterial ou venosa",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        codigoCID: "A00",
        idPrestador: 4,
        idPessoa: 4,
        idProcedimento: 4,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta odontológica",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        codigoCID: "A01",
        idPrestador: 4,
        idPessoa: 5,
        idProcedimento: 5,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Herniorrafia umbilical",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "MEDIO",
        prontoSocorro: false,
        UTI: true,
        tipoInternacao: "PEDIATRICA",
        situacao: "PENDENTE",
        reembolso: true,
        codigoCID: "A01",
        idPrestador: 1,
        idPessoa: 5,
        idProcedimento: 5,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "PENDENTE",
        reembolso: true,
        codigoCID: "B34",
        idPrestador: 2,
        idPessoa: 10,
        idProcedimento: 6,
      },
      {
        dataRealizacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 2,
          dataAtual.getDate() + 10
        ),
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Herniorrafia umbilical",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "MEDIO",
        prontoSocorro: true,
        UTI: true,
        tipoInternacao: "OBSTETRICA",
        tipoParto: "VAGINAL",
        situacao: "NEGADA",
        reembolso: true,
        codigoCID: "A02",
        idPrestador: 3,
        idPessoa: 2,
        idProcedimento: 6,
        teveInternacao: true,
      },
      {
        dataRealizacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 25,
          dataAtual.getDate() + 10
        ),
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "MEDIO",
        UTI: true,
        tipoParto: "CESAREO",
        situacao: "CANCELADA",
        reembolso: true,
        codigoCID: "J80",
        idPrestador: 3,
        idPessoa: 2,
        idProcedimento: 7,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - por dia subsequente de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "ALTO",
        prontoSocorro: true,
        UTI: false,
        tipoInternacao: "PSIQUIATRICA",
        situacao: "PENDENTE",
        reembolso: true,
        codigoCID: "A02",
        idPrestador: 3,
        idPessoa: 2,
        idProcedimento: 7,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "BAIXO",
        situacao: "NEGADA",
        reembolso: false,
        codigoCID: "B34",
        idPrestador: 4,
        idPessoa: 3,
        idProcedimento: 8,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - por dia subsequente de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "ALTO",
        prontoSocorro: true,
        UTI: true,
        tipoInternacao: "CLINICA",
        situacao: "LIBERADA",
        reembolso: true,
        codigoCID: "B34",
        idPrestador: 4,
        idPessoa: 3,
        idProcedimento: 8,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 4,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "PENDENTE",
        reembolso: true,
        codigoCID: "U04",
        idPrestador: 1,
        idPessoa: 4,
        idProcedimento: 9,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 4,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - por dia subsequente de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "MEDIO",
        prontoSocorro: false,
        UTI: true,
        tipoInternacao: "CLINICA",
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "U04",
        idPrestador: 1,
        idPessoa: 4,
        idProcedimento: 9,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 4,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "ALTO",
        prontoSocorro: true,
        UTI: true,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "A00",
        idPrestador: 2,
        idPessoa: 5,
        idProcedimento: 10,
      },
      {
        dataRealizacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 11,
          dataAtual.getDate()
        ),
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 4,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Hemo",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "ALTO",
        prontoSocorro: true,
        UTI: true,
        tipoInternacao: "PEDIATRICA",
        tipoParto: "VAGINAL",
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "U04",
        idPrestador: 1,
        idPessoa: 4,
        idProcedimento: 10,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 1,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "ALTO",
        prontoSocorro: true,
        UTI: true,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "A01",
        idPrestador: 3,
        idPessoa: 1,
        idProcedimento: 11,
      },
      {
        dataRealizacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 11,
          dataAtual.getDate()
        ),
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 1,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Hemo",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: true,
        tipoInternacao: "CLINICA",
        tipoParto: "VAGINAL",
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "A02",
        idPrestador: 4,
        idPessoa: 5,
        idProcedimento: 11,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "ALTO",
        prontoSocorro: false,
        UTI: true,
        situacao: "LIBERADA",
        reembolso: true,
        codigoCID: "A02",
        idPrestador: 4,
        idPessoa: 2,
        idProcedimento: 12,
      },
      {
        dataRealizacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 1,
          dataAtual.getDate() + 10
        ),
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Hemo",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "ALTO",
        prontoSocorro: false,
        UTI: true,
        tipoInternacao: "OBSTETRICA",
        tipoParto: "CESAREO",
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "J80",
        idPrestador: 4,
        idPessoa: 3,
        idProcedimento: 12,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "ALTO",
        prontoSocorro: false,
        UTI: false,
        situacao: "NEGADA",
        reembolso: false,
        codigoCID: "A02",
        idPrestador: 4,
        idPessoa: 2,
        idProcedimento: 12,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - planejamento e 1º dia de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "ALTO",
        prontoSocorro: false,
        UTI: false,
        situacao: "PENDENTE",
        reembolso: false,
        codigoCID: "J80",
        idPrestador: 4,
        idPessoa: 3,
        idProcedimento: 12,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "ALTO",
        prontoSocorro: false,
        UTI: true,
        situacao: "PENDENTE",
        reembolso: true,
        codigoCID: "J80",
        idPrestador: 1,
        idPessoa: 3,
        idProcedimento: 13,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - planejamento e 1º dia de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "ALTO",
        prontoSocorro: true,
        UTI: true,
        tipoInternacao: "PSIQUIATRICA",
        situacao: "NEGADA",
        reembolso: false,
        codigoCID: "J80",
        idPrestador: 1,
        idPessoa: 3,
        idProcedimento: 13,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "ALTO",
        prontoSocorro: false,
        UTI: true,
        situacao: "CANCELADA",
        reembolso: true,
        codigoCID: "B34",
        idPrestador: 2,
        idPessoa: 6,
        idProcedimento: 14,
      },
      {
        dataRealizacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 6,
          dataAtual.getDate() + 10
        ),
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Terapia oncológica - planejamento e 1º dia de tratamento",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "ALTO",
        prontoSocorro: true,
        UTI: true,
        tipoInternacao: "CIRURGICA",
        tipoParto: "CESAREO",
        situacao: "PENDENTE",
        reembolso: false,
        codigoCID: "U04",
        idPrestador: 4,
        idPessoa: 6,
        idProcedimento: 14,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 2,
          dataAtual.getDate() + 10
        ),
        quantidade: 3,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "ALTO",
        prontoSocorro: false,
        UTI: false,
        tipoParto: "CESAREO",
        situacao: "CANCELADA",
        reembolso: false,
        codigoCID: "U04",
        idPrestador: 3,
        idPessoa: 4,
        idProcedimento: 15,
      },
      {
        dataRealizacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 1,
          dataAtual.getDate() + 10
        ),
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 3,
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - planejamento e 1º dia de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "ALTO",
        prontoSocorro: true,
        UTI: false,
        tipoInternacao: "PSIQUIATRICA",
        tipoParto: "VAGINAL",
        situacao: "PENDENTE",
        reembolso: false,
        codigoCID: "A00",
        idPrestador: 4,
        idPessoa: 5,
        idProcedimento: 15,
        teveInternacao: true,
      },
      {
        dataRealizacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 30,
          dataAtual.getDate() + 10
        ),
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "ALTO",
        prontoSocorro: false,
        UTI: true,
        tipoParto: "CESAREO",
        situacao: "CANCELADA",
        reembolso: false,
        codigoCID: "A00",
        idPrestador: 4,
        idPessoa: 5,
        idProcedimento: 16,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - planejamento e 1º dia de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "ALTO",
        prontoSocorro: true,
        UTI: true,
        tipoInternacao: "CLINICA",
        situacao: "PENDENTE",
        reembolso: false,
        codigoCID: "A01",
        idPrestador: 1,
        idPessoa: 1,
        idProcedimento: 16,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Terapia oncológica - planejamento e 1º dia de tratamento",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "ALTO",
        prontoSocorro: true,
        UTI: true,
        tipoInternacao: "CLINICA",
        situacao: "PENDENTE",
        reembolso: false,
        codigoCID: "A01",
        idPrestador: 1,
        idPessoa: 7,
        idProcedimento: 16,
        teveInternacao: true,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "A00",
        idPrestador: 4,
        idPessoa: 7,
        idProcedimento: 16,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 75.5, max: 15000.69 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 75.5, max: 10000 }),
        coparticipacao: faker.number.float({ min: 75.5, max: 10000 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "A00",
        idPrestador: 3,
        idPessoa: 8,
        idProcedimento: 15,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 1500 }),
        descricao: "Consulta geral",
        sinistro: faker.number.float({ min: 10, max: 1200 }),
        coparticipacao: faker.number.float({ min: 10, max: 1200 }),
        risco: "MEDIO",
        prontoSocorro: true,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "B34",
        idPrestador: 1,
        idPessoa: 8,
        idProcedimento: 14,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Identificação vírus",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "ALTO",
        prontoSocorro: true,
        UTI: true,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "B34",
        idPrestador: 1,
        idPessoa: 9,
        idProcedimento: 14,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 20
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Screening",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "B34",
        idPrestador: 1,
        idPessoa: 1,
        idProcedimento: 17,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 15
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Screening",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "B34",
        idPrestador: 1,
        idPessoa: 1,
        idProcedimento: 18,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 1,
          dataAtual.getDate()
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Screening",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "A00",
        idPrestador: 2,
        idPessoa: 2,
        idProcedimento: 19,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 2,
          dataAtual.getDate()
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Screening",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "A00",
        idPrestador: 2,
        idPessoa: 1,
        idProcedimento: 20,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 25
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Screening",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "A00",
        idPrestador: 2,
        idPessoa: 3,
        idProcedimento: 21,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 8
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Screening",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "A00",
        idPrestador: 1,
        idPessoa: 4,
        idProcedimento: 22,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 2,
          dataAtual.getDate()
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Screening",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "A00",
        idPrestador: 1,
        idPessoa: 4,
        idProcedimento: 23,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 3,
          dataAtual.getDate()
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Screening",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "A00",
        idPrestador: 1,
        idPessoa: 5,
        idProcedimento: 24,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 3,
          dataAtual.getDate()
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Screening",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "A00",
        idPrestador: 1,
        idPessoa: 1,
        idProcedimento: 17,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 1,
          dataAtual.getDate() + 5
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Screening",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "A00",
        idPrestador: 1,
        idPessoa: 6,
        idProcedimento: 18,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 1,
          dataAtual.getDate()
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Screening",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "A00",
        idPrestador: 2,
        idPessoa: 2,
        idProcedimento: 19,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 12
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Screening",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "A00",
        idPrestador: 2,
        idPessoa: 4,
        idProcedimento: 20,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 12
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Consulta Clínico Geral",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "BAIXO",
        prontoSocorro: false,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        codigoCID: "B34",
        idPrestador: 2,
        idPessoa: 10,
        idProcedimento: 15,
      },
      {
        dataRealizacao: dataAtual,
        dataPagamento: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 12
        ),
        quantidade: 1,
        custoTotal: faker.number.float({ min: 20, max: 700 }),
        descricao: "Atendimento Acidente Trabalho",
        sinistro: faker.number.float({ min: 10, max: 600 }),
        coparticipacao: faker.number.float({ min: 10, max: 600 }),
        risco: "MEDIO",
        prontoSocorro: true,
        UTI: false,
        situacao: "LIBERADA",
        reembolso: false,
        idPrestador: 3,
        idPessoa: 10,
        idProcedimento: 10,
      },
    ],
  });
}
