import { PrismaClient } from "@prisma/client";

export async function insertLiberacao(prisma: PrismaClient) {
  const dataAtual = new Date();

  await prisma.liberacao.createMany({
    data: [
      {
        id: 1,
        certificado: 1,
        dependencia: 1,
        contrato: 1,
        subfatura: 1,
        senha: "001",
        diasSolicitacaoSenha: 3,
        diasLiberacaoSenha: 5,
        situacaoSenha: "LIBERADA",
        possuiLiminar: true,
        regimeInternacao: "HOSPITALAR",
        dataSolicitacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 1,
          dataAtual.getDate() + 10
        ),
        dataInternacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 1,
          dataAtual.getDate() + 10
        ),
        idPlano: 1,
        idPrestador: 1,
      },
      {
        id: 2,
        certificado: 2,
        dependencia: 2,
        contrato: 2,
        subfatura: 2,
        senha: "002",
        diasSolicitacaoSenha: 5,
        diasLiberacaoSenha: 5,
        situacaoSenha: "LIBERADA",
        possuiLiminar: true,
        regimeInternacao: "HOSPITAL_DIA",
        dataSolicitacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 1,
          dataAtual.getDate() + 10
        ),
        dataInternacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 1,
          dataAtual.getDate() + 20
        ),
        idPlano: 1,
        idPrestador: 1,
      },
      {
        id: 3,
        certificado: 3,
        dependencia: 3,
        contrato: 3,
        subfatura: 3,
        senha: "003",
        diasSolicitacaoSenha: 10,
        diasLiberacaoSenha: 10,
        situacaoSenha: "NEGADA",
        possuiLiminar: true,
        regimeInternacao: "HOSPITALAR",
        dataSolicitacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 2,
          dataAtual.getDate() + 10
        ),
        idPlano: 1,
        idPrestador: 2,
      },
      {
        id: 4,
        certificado: 4,
        dependencia: 4,
        contrato: 4,
        subfatura: 4,
        senha: "004",
        diasSolicitacaoSenha: 10,
        diasLiberacaoSenha: 10,
        situacaoSenha: "LIBERADA",
        possuiLiminar: false,
        regimeInternacao: "HOSPITALAR",
        dataSolicitacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 2,
          dataAtual.getDate()
        ),
        dataInternacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 2,
          dataAtual.getDate() + 8
        ),
        idPlano: 1,
        idPrestador: 3,
      },
      {
        id: 5,
        certificado: 5,
        dependencia: 5,
        contrato: 5,
        subfatura: 5,
        senha: "005",
        diasSolicitacaoSenha: 5,
        diasLiberacaoSenha: 8,
        situacaoSenha: "NEGADA",
        possuiLiminar: false,
        regimeInternacao: "HOSPITAL_DIA",
        dataSolicitacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 1,
          dataAtual.getDate() + 10
        ),
        idPlano: 1,
        idPrestador: 4,
      },
      {
        id: 6,
        certificado: 6,
        dependencia: 6,
        contrato: 6,
        subfatura: 6,
        senha: "006",
        diasSolicitacaoSenha: 4,
        diasLiberacaoSenha: 4,
        situacaoSenha: "LIBERADA",
        possuiLiminar: false,
        regimeInternacao: "HOSPITALAR",
        dataSolicitacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() + 1,
          dataAtual.getDate() + 20
        ),
        idPlano: 2,
        idPrestador: 1,
      },
      {
        id: 7,
        certificado: 7,
        dependencia: 7,
        contrato: 7,
        subfatura: 7,
        senha: "007",
        diasSolicitacaoSenha: 4,
        diasLiberacaoSenha: 4,
        situacaoSenha: "NEGADA",
        possuiLiminar: false,
        regimeInternacao: "HOSPITALAR",
        dataSolicitacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 3,
          dataAtual.getDate() + 10
        ),
        idPlano: 2,
        idPrestador: 2,
      },
      {
        id: 8,
        certificado: 8,
        dependencia: 8,
        contrato: 8,
        subfatura: 8,
        senha: "008",
        diasSolicitacaoSenha: 4,
        diasLiberacaoSenha: 4,
        situacaoSenha: "LIBERADA",
        possuiLiminar: true,
        regimeInternacao: "HOSPITAL_DIA",
        dataSolicitacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 3,
          dataAtual.getDate() + 4
        ),
        dataInternacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 4
        ),
        idPlano: 2,
        idPrestador: 2,
      },
      {
        id: 9,
        certificado: 9,
        dependencia: 9,
        contrato: 9,
        subfatura: 9,
        senha: "009",
        diasSolicitacaoSenha: 4,
        diasLiberacaoSenha: 4,
        situacaoSenha: "LIBERADA",
        possuiLiminar: false,
        regimeInternacao: "HOSPITAL_DIA",
        dataSolicitacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 3,
          dataAtual.getDate()
        ),
        dataInternacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 3,
          dataAtual.getDate() + 4
        ),
        idPlano: 2,
        idPrestador: 3,
      },
      {
        id: 10,
        certificado: 10,
        dependencia: 10,
        contrato: 10,
        subfatura: 10,
        senha: "010",
        diasSolicitacaoSenha: 4,
        diasLiberacaoSenha: 4,
        situacaoSenha: "LIBERADA",
        possuiLiminar: true,
        regimeInternacao: "HOSPITALAR",
        dataSolicitacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 2,
          dataAtual.getDate()
        ),
        dataInternacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 2,
          dataAtual.getDate() + 4
        ),
        idPlano: 2,
        idPrestador: 4,
      },
      {
        id: 11,
        certificado: 11,
        dependencia: 11,
        contrato: 11,
        subfatura: 11,
        senha: "011",
        diasSolicitacaoSenha: 4,
        diasLiberacaoSenha: 4,
        situacaoSenha: "NEGADA",
        possuiLiminar: true,
        regimeInternacao: "HOSPITAL_DIA",
        dataSolicitacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 2,
          dataAtual.getDate()
        ),
        idPlano: 2,
        idPrestador: 4,
      },
      {
        id: 12,
        certificado: 12,
        dependencia: 12,
        contrato: 12,
        subfatura: 12,
        senha: "012",
        diasSolicitacaoSenha: 4,
        diasLiberacaoSenha: 4,
        situacaoSenha: "LIBERADA",
        possuiLiminar: true,
        regimeInternacao: "HOSPITALAR",
        dataSolicitacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 2,
          dataAtual.getDate()
        ),
        dataInternacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 2,
          dataAtual.getDate() + 4
        ),
        idPlano: 3,
        idPrestador: 1,
      },
      {
        id: 13,
        certificado: 13,
        dependencia: 13,
        contrato: 13,
        subfatura: 13,
        senha: "013",
        diasSolicitacaoSenha: 4,
        diasLiberacaoSenha: 4,
        situacaoSenha: "LIBERADA",
        possuiLiminar: false,
        regimeInternacao: "HOSPITAL_DIA",
        dataSolicitacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 2,
          dataAtual.getDate()
        ),
        dataInternacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 2,
          dataAtual.getDate() + 4
        ),
        idPlano: 3,
        idPrestador: 2,
      },
      {
        id: 14,
        certificado: 14,
        dependencia: 14,
        contrato: 14,
        subfatura: 14,
        senha: "014",
        diasSolicitacaoSenha: 4,
        diasLiberacaoSenha: 4,
        situacaoSenha: "LIBERADA",
        possuiLiminar: true,
        regimeInternacao: "HOSPITALAR",
        dataSolicitacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 1,
          dataAtual.getDate()
        ),
        dataInternacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 1,
          dataAtual.getDate() + 4
        ),
        idPlano: 3,
        idPrestador: 3,
      },
      {
        id: 15,
        certificado: 15,
        dependencia: 15,
        contrato: 15,
        subfatura: 15,
        senha: "015",
        diasSolicitacaoSenha: 4,
        diasLiberacaoSenha: 4,
        situacaoSenha: "LIBERADA",
        possuiLiminar: false,
        regimeInternacao: "HOSPITAL_DIA",
        dataSolicitacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 1,
          dataAtual.getDate()
        ),
        dataInternacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth() - 1,
          dataAtual.getDate() + 4
        ),
        idPlano: 3,
        idPrestador: 4,
      },
      {
        id: 16,
        certificado: 16,
        dependencia: 16,
        contrato: 16,
        subfatura: 16,
        senha: "016",
        diasSolicitacaoSenha: 4,
        diasLiberacaoSenha: 4,
        situacaoSenha: "NEGADA",
        possuiLiminar: true,
        regimeInternacao: "HOSPITAL_DIA",
        dataSolicitacao: new Date(
          dataAtual.getFullYear(),
          dataAtual.getMonth(),
          dataAtual.getDate() + 10
        ),
        idPlano: 3,
        idPrestador: 1,
      },
      {
        id: 17,
        certificado: 17,
        dependencia: 17,
        contrato: 17,
        subfatura: 17,
        senha: "017",
        diasSolicitacaoSenha: 4,
        diasLiberacaoSenha: 4,
        situacaoSenha: "NEGADA",
        possuiLiminar: false,
        regimeInternacao: "HOSPITALAR",
        dataSolicitacao: dataAtual,
        idPlano: 3,
        idPrestador: 2,
      },
    ],
  });
}
